services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID} # to correspond to TrueNAS permissions
      - PGID=${PGID} # to correspond to TrueNAS permissions
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://192.168.79.8 #optional
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/data:/data
      - /mnt/media:/media
    devices:
      - /dev/dri:/dev/dri #Use for Intel QuickSync
    ports:
      - 8096:8096
      - 7359:7359/udp #Service Discovery
      - 1900:1900/udp #Client Discovery
    restart: unless-stopped
# Remove the Jellyfin service if installed directly on system.

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=${PUID} # to correspond to TrueNAS permissions
      - PGID=${PGID} # to correspond to TrueNAS permissions
      - TZ=${TZ}
    volumes:
      - /opt/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
